### ISSUE TITLE
Following/unfollowing in separate client is not represented in damus

### ISSUE THREAD

**Issue by benthecarman** [damus-io/damus#1747] opened 2023-11-21 09:34 UTC
Recently I unfollowed the hacker news account when using primal ![image](https://github.com/damus-io/damus/assets/15256660/c980e723-9d2e-44b3-a319-80060e214e00)

However it still shows up in my home feed ![image](https://github.com/damus-io/damus/assets/15256660/084fdc90-a6da-4c6a-90ee-7b790050c66b)

I am guessing there is some cache that is only updated when changes to the follow list are made locally and doesn't update based on what the latest follow list is

**Comment by benthecarman** [comment] 2024-01-04 11:09
I think it's actually that unfollowing just doesn't work in general. There's several people I've unfollowed but still show up in my feed

**Comment by alltheseas** [comment] 2024-04-08 01:46
> I think it's actually that unfollowing just doesn't work in general. There's several people I've unfollowed but still show up in my feed 

I believe this is a duplicate of https://github.com/damus-io/damus/issues/1483

**Closed** 2024-04-08 01:46 UTC
Labels: duplicate, Needs recreation, interop
