### ISSUE TITLE
Wrapped text draft note display issue when composing note and mentioning npub [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1211] opened 2023-05-31 03:13 UTC
_what happens_
When I write a line, and on the next tag someone the wrap text breaks and expands out of screen/when it shouldn't 

_what I think should happen_
I should be able to see my note draft even when I tag a npub

https://github.com/damus-io/damus/assets/64376233/f368f457-3939-4492-9c95-bff40812e44a

1.5 (2) and (3) by Matthieu

https://damus.io/note1smk5hmfzfh395lt74yafvtke4avvxva8kpmh3tl2ngejruftfqdsxnkq7a

**Comment by alltheseas** [comment] 2023-06-18 02:26
https://github.com/damus-io/damus/assets/64376233/5a373931-54ce-47f9-90c1-15d931e4d34a

From JeffT

npub108kuptq55xrxqc8ttfjqwwhkh7ruur7d3drm2yyp8ul9t86w9g0s3v9usw

**Comment by alltheseas** [comment] 2023-07-30 15:25
Tanel: https://damus.io/note103mmjrchat8rhkm53y8e0dms86zx6xw6qacnsewxac0w387xupus8d532z

**Comment by danieldaquino** [comment] 2023-09-15 19:36
**Update:** Currently working on this, I have determined the root cause, now I am working on a fix that does not break the remaining layout. More updates coming soon!

**Comment by danieldaquino** [comment] 2023-09-16 03:36
I have a fix for this issue. It is not 100% yet, but hopefully it improves the composer.

There were other issues that were uncovered as soon as I fixed this one, which made the text editor almost unusable, so I had to make some other improvements as well to prevent the text editor from regressing.

It's very tricky to get it done perfectly because a lot of the text editor functionality and layout is intricate and interconnected. Besides, I have also identified some quirks with SwiftUI and UIKit itself.

Overall there are still a few quirks with the text editor, which we might want to address but hopefully this fix will bring things to a better state.

## Root cause and fix

The root cause I have identified is that once the user starts tagging a user and the contact list shows up, the post view causes `TextViewWrapper` to disable scrolling on its `UITextInput`.

However, `UITextInput` has a quirk which causes lines to not wrap as soon as scrolling is disabled. It seems to always do that even if we constrain its own frame via UIKit directly or via its SwiftUI wrapper.

I could not find any setting that could change this behaviour in the [developer documentation](https://developer.apple.com/documentation/uikit/uitextinputtraits), so leaving the `UITextInput` with scrolling enabled seems to be the only way to fix the issue.

### Cursor out-of-view issue caused by fixing the text wrapping issue

In an effort to discover why we enabled and disabled scrolling dynamically on the `UITextInput`, I did a bit of investigation. It seems that this logic dates back to May 2023, and this was added to prevent cases where the cursor would disappear when typing longer messages.

I believe it is associated with this changelog entry:
```
Fix issue where cursor dissapears when typing long message
```

I tested on my end, and confirmed leaving `UITextInput` scrolling always enabled caused the cursor to go out of view on longer messages as well as when typing mentions on longer wrapped lines. This makes the text editor significantly harder to use.

So, to fix the issue in this ticket and prevent a regression at the same time, I needed to make further changes.

### Preventing regression on the cursor-out-of-view issue

To make this fix without regressions, I made the following changes:
1. Leave UITextInput scrolling always enabled (to prevent the unwrapping behaviour from `UITextInput`)
2. Scroll the text caret into view anytime its vertical position moves, or when the contact list panel is toggled. To allow cross-communication between the relevant SwiftUI and UIKit components (which use significantly different APIs), I had to create an intermediary object — a "ghost" text caret which follows the real text caret and is used for scrolling the `ScrollView` into its position. More details are documented on the code.
3. Dynamically change the height of `UITextInput` to fit its text, to prevent vertical scrolling on the text box, and having a scrolling view inside of a scrolling view (which makes it harder to navigate, and causes misalignment with the new ghost text caret).
4. (A few other small layout improvements to avoid issues, more details on the code)

## The fix

### Patch

Patch was sent via email and can be seen at: [https://groups.google.com/a/damus.io/g/patches/c/osrUXmTUPfo](https://groups.google.com/a/damus.io/g/patches/c/osrUXmTUPfo)

### Testing

**CONDITIONAL PASS**

**iOS:**
- 16.4 (iPhone 14 Pro simulator)
- 17.0 (iPhone 14 Pro simulator)

**Damus:** `dd11fecd66a281a013f8d3537919588dbc45c8c1`
**Test steps and results:**
| Step # | Step | Expected results | Actual results |
|-----|----|------|------|
| 1 | Open the note composer view | Should open | works |
| 2 | Type a bit of text | Should work | works |
| 3 | Type a mention | Should work | works | 
| 4 | Type several words within the same line, then start to type a user mention | Make sure that: (1) Text does not unwrap itself and does not overflow horizontally. (2) View is scrolled up until the text cursor (or caret) is visible. (3) View stays in position and is not jittery as characters are typed | Works as expected | 
| 5 | Start adding a few newlines | Make sure adding them does not cause any jitter | Works |
| 6 | Type a mention in the beginning of a newline | make sure that it scrolls into view | Works |
| 7 | Start adding a bunch of new lines to the point it goes beyond the screen height | Make sure that cursor is still visible | Works 100% of the time on iOS 17. On iOS 16 it often works, but sometimes it does not follow the cursor |
| 8 | Copy and paste a piece of text into the editor | Make sure that it works as expected | _It briefly hides the start of the text until the user hits return_ |
| 9 | Try steps 1 – 7, but this time replying to a post | (Follow expectations on steps 1 – 7) | Same behaviour as documented above, and layout when replying to posts seems to be working |
| 10 | Try steps 1 – 7, but this time with an image attachment | (Follow expectations on steps 1 – 7) | Same behaviour as documented above, and layout with an image attachment is working |

**Videos:** Since this test covers very visual-oriented functionality, I have recorded videos to document my testing. Hopefully that makes it easier to understand how well the patch is working
- [Steps 1–8 video](https://drive.google.com/file/d/1-uEgmNl-Vt9_BrbdaPHKRtePi-vGOKy2/view?usp=sharing)
- [Steps 9–10 video](https://drive.google.com/file/d/1gQqk2KyoKsq55IdBMYxNMLqJmk4BJJ6n/view?usp=sharing)

## Conclusion

I apologize the fix not being simpler than this, this area of code is very intricate and interconnected in a way that makes it difficult to fully fix things without affecting other behavior.

Although I could not get something 100% flawless yet, I hope this patch brings the editor to a better state. 

I could continue refining this in this ticket, or we could split up the remaining quirks into different tasks (whichever works best).

@jb55, @alltheseas, please let me know if you have any suggestions, questions, or concerns. Thank you very much for reviewing!

**Comment by alltheseas** [comment] 2023-09-16 15:02
I'm aligned with your diagnosis and proposed fix @danieldaquino 

Thanks for the detailed investigation.

**Comment by jb55** [comment] 2023-09-16 18:40
On Fri, Sep 15, 2023 at 08:36:36PM -0700, Daniel D’Aquino wrote:
>I have a fix for this issue. It is not 100% yet, but hopefully it improves the composer.
>
>There were other issues that were uncovered as soon as I fixed this one, which made the text editor almost unusable, so I had to make some other improvements as well to prevent the text editor from regressing.
>
>It's very tricky to get it done perfectly because a lot of the text editor functionality and layout is intricate and interconnected. Besides, I have also identified some quirks with SwiftUI and UIKit itself.
>
>Overall there are still a few quirks with the text editor, which we might want to address but hopefully this fix will bring things to a better state.
>
>## Root cause and fix
>
>The root cause I have identified is that once the user starts tagging a user and the contact list shows up, the post view causes `TextViewWrapper` to disable scrolling on its `UITextInput`.
>
>However, `UITextInput` has a quirk which causes lines to not wrap as soon as scrolling is disabled. It seems to always do that even if we constrain its own frame via UIKit directly or via its SwiftUI wrapper.
>
>I could not find any setting that could change this behaviour in the [developer documentation](https://developer.apple.com/documentation/uikit/uitextinputtraits), so leaving the `UITextInput` with scrolling enabled seems to be the only way to fix the issue.
>
>### Cursor out-of-view issue caused by fixing the text wrapping issue
>
>In an effort to discover why we enabled and disabled scrolling dynamically on the `UITextInput`, I did a bit of investigation. It seems that this logic dates back to May 2023, and this was added to prevent cases where the cursor would disappear when typing longer messages.
>
>I believe it is associated with this changelog entry:
>```
>Fix issue where cursor dissapears when typing long message
>```
>
>I tested on my end, and confirmed leaving `UITextInput` scrolling always enabled caused the cursor to go out of view on longer messages as well as when typing mentions on longer wrapped lines. This makes the text editor significantly harder to use.
>
>So, to fix the issue in this ticket and prevent a regression at the same time, I needed to make further changes.
>
>### Preventing regression on the cursor-out-of-view issue
>
>To make this fix without regressions, I made the following changes:
>1. Leave UITextInput scrolling always enabled (to prevent the unwrapping behaviour from `UITextInput`)
>2. Scroll the text caret into view anytime its vertical position moves, or when the contact list panel is toggled. To allow cross-communication between the relevant SwiftUI and UIKit components (which use significantly different APIs), I had to create an intermediary object — a "ghost" text caret which follows the real text caret and is used for scrolling the `ScrollView` into its position. More details are documented on the code.
>3. Dynamically change the height of `UITextInput` to fit its text, to prevent vertical scrolling on the text box, and having a scrolling view inside of a scrolling view (which makes it harder to navigate, and causes misalignment with the new ghost text caret).
>4. (A few other small layout improvements to avoid issues, more details on the code)
>
>## The fix
>
>### Patch
>
>Patch was sent via email and can be seen at: [https://groups.google.com/a/damus.io/g/patches/c/osrUXmTUPfo](https://groups.google.com/a/damus.io/g/patches/c/osrUXmTUPfo)
>
>### Testing
>
>**CONDITIONAL PASS**
>
>**iOS:**
>- 16.4 (iPhone 14 Pro simulator)
>- 17.0 (iPhone 14 Pro simulator)
>
>**Damus:** `dd11fecd66a281a013f8d3537919588dbc45c8c1`
>**Test steps and results:**
>| Step # | Step | Expected results | Actual results |
>|-----|----|------|------|
>| 1 | Open the note composer view | Should open | works |
>| 2 | Type a bit of text | Should work | works |
>| 3 | Type a mention | Should work | works |
>| 4 | Type several words within the same line, then start to type a user mention | Make sure that: (1) Text does not unwrap itself and does not overflow horizontally. (2) View is scrolled up until the text cursor (or caret) is visible. (3) View stays in position and is not jittery as characters are typed | Works as expected |
>| 5 | Start adding a few newlines | Make sure adding them does not cause any jitter | Works |
>| 6 | Type a mention in the beginning of a newline | make sure that it scrolls into view | Works |
>| 7 | Start adding a bunch of new lines to the point it goes beyond the screen height | Make sure that cursor is still visible | Works 100% of the time on iOS 17. On iOS 16 it often works, but sometimes it does not follow the cursor |
>| 8 | Copy and paste a piece of text into the editor | Make sure that it works as expected | _It briefly hides the start of the text until the user hits return_ |
>| 9 | Try steps 1 – 7, but this time replying to a post | (Follow expectations on steps 1 – 7) | Same behaviour as documented above, and layout when replying to posts seems to be working |
>| 10 | Try steps 1 – 7, but this time with an image attachment | (Follow expectations on steps 1 – 7) | Same behaviour as documented above, and layout with an image attachment is working |
>
>**Videos:** Since this test covers very visual-oriented functionality, I have recorded videos to document my testing. Hopefully that makes it easier to understand how well the patch is working
>- [Steps 1–8 video](https://drive.google.com/file/d/1-uEgmNl-Vt9_BrbdaPHKRtePi-vGOKy2/view?usp=sharing)
>- [Steps 9–10 video](https://drive.google.com/file/d/1gQqk2KyoKsq55IdBMYxNMLqJmk4BJJ6n/view?usp=sharing)
>
>## Conclusion
>
>I apologize the fix not being simpler than this, this area of code is very intricate and interconnected in a way that makes it difficult to fully fix things without affecting other behavior.

Yes we will likely need to refactor these components, because changing
them seems to lead to exploding amounts of complexity each time :(

	Will

**Closed** 2023-09-16 19:17 UTC
Labels: bug 🐞

**Comment by danieldaquino** [comment] 2023-09-16 19:26
>>
>>I apologize the fix not being simpler than this, this area of code is very intricate and interconnected in a way that makes it difficult to fully fix things without affecting other behavior.
>
> Yes we will likely need to refactor these components, because changing
> them seems to lead to exploding amounts of complexity each time :(
>
> Will

By the way, this morning I searched a bit more and found one page in the Apple developer documentation that could be useful in making the text editor more robust: https://developer.apple.com/documentation/uikit/textkit/display_text_with_a_custom_layout

I haven’t tested it yet, but this might allow us to do text wrapping without having to leave `isScrollEnabled = true` and without having to dynamically change the text box height in response to text changes (which might improve robustness in certain edge cases like copy/paste).

Hopefully this is something that can help us in refactoring this text editor.

Best regards,
Daniel

**Comment by danieldaquino** [comment] 2023-09-16 19:56
On Sat, Sep 16, 2023 at 07:26:29PM +0000, Daniel D'Aquino wrote:
>By the way, this morning I searched a bit more and found one page in the Apple developer documentation that could be useful in making the text editor more robust: https://developer.apple.com/documentation/uikit/textkit/display_text_with_a_custom_layout
>
>I haven’t tested it yet, but this might allow us to do text wrapping without having to leave `isScrollEnabled = true` and without having to dynamically change the text box height in response to text changes (which might improve robustness in certain edge cases like copy/paste).

Is this a simple fix? Would be happy if you wanted to take a stab at it
but I also don't want to burn too many cycles on it at this exact moment
if its a big refactor.

**Comment by danieldaquino** [comment] 2023-09-18 17:31
> On Sep 16, 2023, at 12:55, William Casarin ***@***.***> wrote:
> 
> Is this a simple fix? Would be happy if you wanted to take a stab at it
> but I also don't want to burn too many cycles on it at this exact moment
> if its a big refactor.

At the surface it does not seem too complex, but given that the functionality in this area is highly interconnected, I imagine there could be an unintended side-effect that causes the fix to be more complex.

Perhaps I can spend 30 minutes on it and either send the patch if it’s done, or write up a Github issue with my investigation so that we can pick up some other time?
