### ISSUE TITLE
Bug: tapping pfp is difficult

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2495] opened 2024-09-19 09:28 UTC
**What happens**
When I perform try to tap pfp it is a struggle. 

**What I expect to happen**
Revert to prior working hitboxes. 

**Link to noteID, npub**

https://damus.io/nevent1qqspmagsyw03txk3e7aawavyjn5w5x097jj7tmke6j5ysjg2uk26qrgpz4mhxue69uhhyetvv9ujumt0wd68ytnsw43qzsmhwvaz7tejdfekumrgvehx2mrfvu6kzcm3xe5kzcmev3kh5erzv3kkwdmcwa6kumf50pkrvuthvfm85ctrwu6xcamjdfkkc7ty9ehku6t0dcq32amnwvaz7tmhda6zuum0we3xjapwdphhxaqpzfmhxue69uhhwmm59e6hg7r09ehkuegwf69ps

![image](https://github.com/user-attachments/assets/b064027c-cbca-4dbc-a94b-e8fcb8a9795f)

1.10 (9) 6254cea6

**Comment by jb55** [comment] 2024-09-19 09:30
Duplicate of https://github.com/damus-io/damus/issues/2370

**Closed** 2024-09-19 09:30 UTC
Labels: bug, design, Needs recreation, unexpected
