### ISSUE TITLE
Long form note nostr:npub mentions not rendering

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1743] opened 2023-11-19 22:27 UTC
![image](https://github.com/damus-io/damus/assets/64376233/4a45d2b8-3b88-42d4-aae5-1b2e68ba25c8)

https://damus.io/note12zmgfeze462wsv7ugx3wq8ae2hdmf68eu2ua7f7n6236hzhlg2msl57pf7

![image](https://github.com/damus-io/damus/assets/64376233/77487f3f-7dd5-48e6-800c-735d442811ac)

**Comment by kernelkind** [comment] 2023-12-20 19:13
I cannot reproduce this

**Comment by alltheseas** [comment] 2023-12-20 19:24
@jb55 was this fixed with nostrdb updates?

**Comment by jb55** [comment] 2023-12-20 20:23
On Wed, Dec 20, 2023 at 11:13:14AM -0800, kernelkind wrote:
>I cannot reproduce this

Are you testing long a longform note? they are definitely not rendered
there because we are using a markdown library.

Ideally we would just fork the one we are using and add nostr:mention
support. Or we could take a look at how nostur is doing it

**Comment by alltheseas** [comment] 2024-02-15 18:48
@kernelkind similar problem to the translated notes you identified 👀

**Comment by jb55** [comment] 2024-04-08 20:02
Duplicate of

- https://github.com/damus-io/damus/issues/1563

**Closed by jb55** 2024-04-08 20:02 UTC
Labels: unexpected, longform
