### ISSUE TITLE
Create highlights on longform notes

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1435] opened 2023-08-04 12:55 UTC
Once we have longform note text selection, it would be nice if there was an option tonight highlight / quote repost a part of the post.

Displaying highlights would be awesome as well.

**Comment by alltheseas** [comment] 2023-08-04 15:00
Is this a duplicate of https://github.com/damus-io/damus/issues/822

**Comment by jb55** [comment] 2023-08-04 16:43
On Fri, Aug 04, 2023 at 08:01:01AM -0700, alltheseas wrote:
>Is this a duplicate of https://github.com/damus-io/damus/issues/822

looks like it. I think we should only have this for longform notes 🤔

not sure if it makes sense for kind 1.

**Closed** 2023-08-04 17:11 UTC
