### ISSUE TITLE
Sometimes blurred videos are unopenable in universe view

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1247] opened 2023-06-04 20:22 UTC
WIP

Example blurred videos

https://github.com/damus-io/damus/assets/64376233/a21ea945-c0e9-4140-b75d-5cf30a075205

https://damus.io/note167feyf9tgyp96u4g5zh9rw35nm5v3pvfj88g4qhdfqf9ryyjh5uqmpn5nm

https://damus.io/note1al257h7ryzme59nmlvn68ytefgzwww4h37v6yd59acpfruxsavaqmgjujw

@bryanmontz

**Comment by alltheseas** [comment] 2023-06-04 21:56
From @bryanmontz https://damus.io/note1upc4z0mg8t3s65c3cv2z845ss0ga0sk9tu5j6hmn2d28gpytts4sjwlnyz

**Comment by danieldaquino** [comment] 2023-09-13 19:10
I will try to write a fix for this one 👍

**Comment by danieldaquino** [comment] 2023-09-13 21:10
I was able to create a fix for this, by slightly changing the blur layer behaviour.

I also setup the iOS 17 SDKs on my dev environment _(had to free up some disk space for that LOL)_ so that I can start testing Damus on both OS versions, since iOS 17 is coming up soon.

## Issue repro

**iOS:** 16.4 (iPhone 14 Pro simulator)
**Damus:** 1.6 (17) `b1e0a6210987da97f0b3c66ce58ef85b6cb3c3d1` (Current tip of `master`)
**Steps:**
1. Go to search tab
2. Search for `note167feyf9tgyp96u4g5zh9rw35nm5v3pvfj88g4qhdfqf9ryyjh5uqmpn5nm`
3. Tap the blurred video

**Ideal behaviour:** Video should become viewable
**Actual behaviour:** Video stays blurred and is not viewable

## Root cause and fix

Damus uses a ZStack with a non-clickable Blur layer on top to hide certain media. 
- When the media is a picture, clicking the blurry picture opens a fullscreen view, where the user can view the image.
- However, fullscreen videos are not yet supported. so clicking on a blurry video does not do anything.

To fix this, I changed the behaviour a little bit:
- Users can now click on the blurry image/video to reveal it.
- On pictures, users can click on it a second time to open the fullscreen image view 
- The blurry layer returns as soon as the note view is unloaded and reloaded (e.g. If the user switches to a different tab, or if Damus is restarted)

Although the behaviour is changed a bit, I believe it's still very intuitive, and brings the additional advantage that one can go through a list of blurry notes faster _(Since they only need to tap them once to reveal, instead of tapping and then tapping on "close" to go back to the feed)_

## Patch

The patch can be found at: [https://groups.google.com/a/damus.io/g/patches/c/GR1cArW_UZo](https://groups.google.com/a/damus.io/g/patches/c/GR1cArW_UZo)

## Testing

**PASS**

**iOS:** 
- 17.0 (iPhone 14 Pro simulator)
- 16.4 (iPhone 14 Pro simulator)

**Damus:** 1.6 (17) `704dc5ad71e839f18912a0169488caf0e374795b` (New patch)
**Steps:**
1. Go to search/universe tab
2. Search for `note167feyf9tgyp96u4g5zh9rw35nm5v3pvfj88g4qhdfqf9ryyjh5uqmpn5nm`
3. Tap the blurred video to unblur (Should unblur)
4. Look for other blurred images in the search/universe tab
5. Tap them to unblur (Should unblur)
6. Tap them once again for the fullscreen view (Should become fullscreen)
7. Go to the home tab
8. Go back to the search/universe tab
9. Search for the same note: `note167feyf9tgyp96u4g5zh9rw35nm5v3pvfj88g4qhdfqf9ryyjh5uqmpn5nm`
10. Check that video is blurred (Should be blurred)

**Results:** The behaviour matches expectations above on both iOS versions tested.

**Closed** 2023-09-16 19:17 UTC
Labels: bug 🐞, video 🎥
