### ISSUE TITLE
Lightning Wallet connection prompt

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1381] opened 2023-07-21 15:09 UTC
When connecting a wallet for the first time, or zapping in the Damus app for the first time after downloading the app, create a prompt to select default settings of amount and Zap Type (Public, Private, Anonymous, None).

**Comment by alltheseas** [comment] 2023-07-22 14:36
Duplicate of 

https://github.com/damus-io/damus/issues/571

**Closed** 2023-07-22 14:37 UTC
