### ISSUE TITLE
Compress videos during upload

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2169] opened 2024-04-18 03:09 UTC
In order to:

1) save upload bandwidth
2) reduce upload time
3) fit videos within 10 MB unpaid account file size limit of damus file hoster nostr.build 

Compress videos to reduce filesize

Origin: @jb55 

https://t.me/damusios/1429

**Comment by alltheseas** [comment] 2024-04-18 03:10
Related:

Image proxy https://github.com/damus-io/damus/issues/2098

**Comment by jb55** [comment] 2024-05-06 20:34
Duplicate of #1510 I think?

**Closed** 2024-05-06 20:34 UTC
Labels: feature, technical, perf, media
