### ISSUE TITLE
Confirm contact list creation during account creation

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2057] opened 2024-03-15 13:50 UTC
## solution

We should only continue onboarding if we get a contact list creation confirmation from the server.

https://damus.io/nevent1qqswkugx9lh2lye8snjxgmwl70p85qeanhe99erm49al04qa9nptsec46djng

## problem observation

I’m suspecting that some unhappy path damus onboarding leads to some limbo state where there is no relay list, or contact list

I could not recreate with two new test profiles. 

## diagnosis

> This can happen if they create an account when they are not connected to
the internet. We should only continue onboarding if we get a contact
list creation confirmation from the server.

**Comment by alltheseas** [comment] 2024-03-15 13:52
@ericholguin confirms independently an additional in person bug report

**Comment by alltheseas** [comment] 2024-03-15 13:56
Bug reported confirmed they have only used Damus, and no other nostr apps.

**Comment by alltheseas** [comment] 2024-03-15 16:21
I am concerned that this is not a one-off, and new folks are dropping off Damus without having a chance to test it.

**Comment by alltheseas** [comment] 2024-03-17 03:10
One more instance https://damus.io/nevent1qqst6s474020ztfe639zj6uld5f83e6fgvfenjqp2rjnkmx6cuyhtmgjwpzu5

**Comment by alltheseas** [comment] 2024-03-17 03:11
@jb55 advises

> This can happen if they create an account when they are not connected to
the internet. We should only continue onboarding if we get a contact
list creation confirmation from the server.

> It can also happen if they are using an older key and it can't find a
contact list

**Comment by alltheseas** [comment] 2024-03-17 03:13
@danieldaquino @jb55 @ericholguin @kernelkind 

Can one of yall grab this to the current sprint? The unhappy path here is a shit experience for new damus users. We have seen an uptick, and I dont want to keep scaring them off due to bread and butter stuff not working. 

Thank yalls 🙏

**Comment by jb55** [comment] 2024-03-17 08:42
On Sat, Mar 16, 2024 at 08:14:21PM -0700, alltheseas wrote:
>@danieldaquino @jb55 @ericholguin @kernelkind
>
>Can one of yall grab this to the current sprint? The unhappy path here is a shit experience for new damus users. We have seen an uptick, and I dont want to keep scaring them off due to bread and butter stuff not working.
>
>Thank yalls 🙏

yeah let's add it to the sprint. I can look into it.

**Comment by alltheseas** [comment] 2024-03-18 16:29
fyi @ericholguin

**Comment by alltheseas** [comment] 2024-04-08 18:19
> I doubt that he had a bad connection. He’s in a regular city afaik. I wonder how many people that has happened to


Feedback from bug reported when I suggested to try keys creation on stable wifi

**Comment by jb55** [comment] 2024-04-09 15:45
> > I doubt that he had a bad connection. He’s in a regular city afaik. I wonder how many people that has happened to
> 
> Feedback from bug reported when I suggested to try keys creation on stable wifi

fwiw I've never been able to reproduce this. anyone else?

**Comment by alltheseas** [comment] 2024-04-09 15:53
I've created dozens of test accounts. Has not happened to me

**Comment by jb55** [comment] 2024-04-09 16:07
this is why I suspect it must have happened when the connection to the relay was down. I can't think of anything else.  "stable wifi" or not.

**Comment by alltheseas** [comment] 2024-04-09 16:34
> this is why I suspect it must have happened when the connection to the relay was down. I can't think of anything else. "stable wifi" or not.

When you say relay, do you mean specifically damus relay?

**Comment by jb55** [comment] 2024-04-09 17:11
On Tue, Apr 09, 2024 at 09:35:02AM GMT, alltheseas wrote:
>> this is why I suspect it must have happened when the connection to the relay was down. I can't think of anything else. "stable wifi" or not.
>
>When you say relay, do you mean specifically damus relay?

would have to be disconnected from all relays in the bootstrap list

**Comment by alltheseas** [comment] 2024-04-10 03:35
Official bug meme dropped

 ![image](https://github.com/damus-io/damus/assets/64376233/ad84944a-4b55-4589-aaf9-784fa5cd2dce)



https://damus.io/nevent1qqspck609tkdftqzcd4ntth20h0w63e9wtv5yc7tsps39t7f9g0ffusppamhxue69uhkummnw3ezumt0d5q36amnwvaz7tmwdaehgu3dwp6kytnhv4kxcmmjv3jhytnwv46qz9rhwden5te0dehhxarj9ehhsarj9ejx2aspp4mhxue69uhkummn9ekx7mqn7tcjs

**Comment by alltheseas** [comment] 2024-04-12 17:10
@danieldaquino this is the onboarding limbo ticket we discussed in today's standup

**Comment by alltheseas** [comment] 2024-04-12 17:12
As discussed moved to 1.8 milestone

cc @jb55

**Comment by jb55** [comment] 2024-04-14 18:31
Another confirmation that the switching is indeed the issue:

https://damus.io/nevent1qqsp6xpqxp7vek2pdrh3nle4nr5400lhtseyam0vchtwr0mj7gxn84qywvdf4

**Comment by danieldaquino** [comment] 2024-04-15 21:58
I haven't been able to fully, properly repro this yet. I have tried:
1. Switching apps during the "Copy your private key" onboarding step. No issues
2. Not saving the nsec on Keychain. No issues
3. Turning off the internet during the "Copy your private key" onboarding step. The view does not allow me to proceed.

Got a very rudimentary/hacky repro working though, by making this change locally:
```diff
diff --git a/damus/Views/SaveKeysView.swift b/damus/Views/SaveKeysView.swift
index 4d7b6399..7a06da45 100644
--- a/damus/Views/SaveKeysView.swift
+++ b/damus/Views/SaveKeysView.swift
@@ -122,7 +122,8 @@ struct SaveKeysView: View {
             switch wsev {
             case .connected:
                 let metadata = create_account_to_metadata(account)
-                let contacts_ev = make_first_contact_event(keypair: account.keypair)
+                var contacts_ev = make_first_contact_event(keypair: account.keypair)
+                contacts_ev = nil   // Simulate a failure in creating the contact event

                 if let keypair = account.keypair.to_full(),
                    let metadata_ev = make_metadata_event(keypair: keypair, metadata: metadata) {
```

If `make_first_contact_event(keypair: account.keypair)` evaluates to `nil`, no contact event is sent to the relays.

When I went through onboarding with this modified code, no follows would ever stick, and my home feed would be permanently empty, similar to the symptoms described

I therefore suspect that `make_first_contact_event(keypair: account.keypair)` is evaluating to `nil` for some reason. I will keep investigating.

**Comment by alltheseas** [comment] 2024-04-15 22:07
One heuristic is no followers, and/or no relay list show on profile

![image](https://github.com/damus-io/damus/assets/64376233/b8089466-e427-44b0-ac62-742164e43fbf)

**Comment by danieldaquino** [comment] 2024-04-15 23:03
> One heuristic is no followers, and/or no relay list show on profile
> 
> ![image](https://private-user-images.githubusercontent.com/64376233/322641769-b8089466-e427-44b0-ac62-742164e43fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjIzNzAsIm5iZiI6MTcxMzIyMjA3MCwicGF0aCI6Ii82NDM3NjIzMy8zMjI2NDE3NjktYjgwODk0NjYtZTQyNy00NGIwLWFjNjItNzQyMTY0ZTQzZmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDIzMDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MGFkZDUyZGMyMzU0NDEyNjc0MjhjNjAxYmZmMGU3OWE1YjIyNDNkMTkxMDRiMzE4OTMzNzY2NWU5Y2NjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Et5VlOE_w0w3gl_wKSWmU_MDBY5pkWa_BEaW3OFNLP0)

@alltheseas, not sure I understand. The followers list is only loaded when tapped on that button, what is the symptom you are describing?

**Comment by alltheseas** [comment] 2024-04-15 23:23
In the pictured profile I shared there is a followers list. Relay list is missing.

On some of the limbo profiles there is no followers list, and there is no relay list.

**Comment by alltheseas** [comment] 2024-04-15 23:23
Affected profiles have either, or both missing.

**Comment by danieldaquino** [comment] 2024-04-16 00:03
> In the pictured profile I shared there is a followers list. Relay list is missing.

Oh I see, thanks for clarifying! I can confirm that the profile created with my hacky repro is also missing the relay list

**Comment by danieldaquino** [comment] 2024-04-16 02:22
I am investigating how to fix this without having a 100% accurate repro. Since my hacky repro worked, I am _assuming_ that one of two things are happening:
- Something goes wrong during the creation of the Nostr event itself, causing it to never be sent, or
- The program fails to send the event, or the relay fails to receive it.

I also verified that if — for whatever reason — the relays lose or delete the contact event from the user (to the point that the user cannot retrieve their contact event), the user will get stuck in this state.

With that in mind, I am organizing this fix into two parts, in order:
1. Improving robustness around the contact management functionality to make sure that we can get users out of this state if they ever fall in it.
2. Improving robustness around onboarding to avoid this from happening in the first place

**Comment by jb55** [comment] 2024-04-17 17:27
> Improving robustness around the contact management functionality to make sure that we can get users out of this state if they ever fall in it.

keep in mind this is very dangerous, which is why I never did it. If connectivity is ever lost and damus thinks it can't find the contact list then overrides it, it can wipe an entire contact list which is realllly bad.

There are cases where people login with an old key from other apps that never had a contact list to begin with, so I agree it's still an important thing to fix.

If we save and retrieve contact lists from nostrdb:

- #1734 

Then this at least eliminiates the problem our end during account creating if the issue is in fact relay connectivity.

I will look into splitting off the nostrdb-update branch so that we can do this quicker instead of having to wait for

- #2121

**Comment by danieldaquino** [comment] 2024-04-17 18:25
> keep in mind this is very dangerous, which is why I never did it. If connectivity is ever lost and damus thinks it can't find the contact list then overrides it, it can wipe an entire contact list which is realllly bad.

Thanks for letting me know about this sharp edge, I will put some extra care into preventing that.

> If we save and retrieve contact lists from nostrdb:
> 
> https://github.com/damus-io/damus/issues/1734
> Then this at least eliminiates the problem our end during account creating if the issue is in fact relay connectivity.
> 
> I will look into splitting off the nostrdb-update branch so that we can do this quicker instead of having to wait for the full
>
> https://github.com/damus-io/damus/pull/2121

Thanks! I will wait for this, and in the meantime I will work on my item 2:
> 2. Improving robustness around onboarding to avoid this from happening in the first place

**Comment by danieldaquino** [comment] 2024-04-17 22:44
> > I will look into splitting off the nostrdb-update branch so that we can do this quicker instead of having to wait for the full
> > #2121
> 
> Thanks! I will wait for this, and in the meantime I will work on my item 2:

Actually, @jb55, do we have the mechanism to subscribe to NostrDB merged into `master`? If so, I can probably get item 1 (Saving contact lists locally) done too

**Comment by danieldaquino** [comment] 2024-04-18 00:31
> 2. Improving robustness around onboarding to avoid this from happening in the first place

Regarding this item, I am more and more convinced that simply hooking up to NostrDB and making sure this contact list event is saved locally will solve most or all the problems here.

Most of the solutions I have in mind for this item will likely become obsolete once we have the ability to save and read this contact list directly to/from NostrDB.

------

On the repro side, I have good news! I was able to more reliably (3/3 tries) repro this issue _(or at least something very similar)_ without resorting to hacky changes of code.

## More stable, less hacky repro

**Device:** iPhone 15 simulator
**iOS:** 17.4
**Setup:**
- [Network link conditioner](https://medium.com/macoclock/how-to-simulate-poor-network-conditions-on-ios-simulator-and-iphone-faf35f0da1b5) setup with the following profile:
  - Download and upload bandwidth: 50 kbps (awfully slow)
  - Packets dropped: 75% (Awful)
  - Connection delay: 1000ms
  - DNS delay: 400ms

**Steps:** 
1. Delete app and reinstall to start from scratch
2. Turn the Network link conditioner ON
3. Go through onboarding
4. When reaching the home screen, quit the app _(to prevent sending that contact list, if it's sitting in any queue somewhere)_
5. Turn the Network link conditioner OFF.
6. Open the app again.
7. Check if the symptoms are present (unable to get a follow to stick, absence of relay list on profile)

**Results:** **Symptoms are present 3 out of 3 tries**

**Comment by danieldaquino** [comment] 2024-04-22 21:24
@jb55 I believe my fix is still incomplete. When I go through the test (similar to the repo in the previous comment) I am now able to actually follow users and get that list persistently saved across app restarts, but I still see some weirdness like posts from those follows not showing up on the home feed. Currently investigating it

**Comment by danieldaquino** [comment] 2024-04-22 21:25
_(I forgot to post it here, but I sent a draft for this fix on Friday: https://groups.google.com/a/damus.io/g/patches/c/B0H8UK5HQNE)_

**Comment by jb55** [comment] 2024-04-22 21:43
On Mon, Apr 22, 2024 at 02:37:01PM -0700, Daniel D’Aquino wrote:
>> @jb55 I believe my fix is still incomplete. When I go through the test (similar to the repo in the previous comment) I am now able to actually follow users and get that list persistently saved across app restarts, but I still see some weirdness like posts from those follows not showing up on the home feed. Currently investigating it
>
>I fixed it! Re-testing with new version

thanks!

**Comment by alltheseas** [comment] 2024-04-22 23:48
Is the first aid always a manual action? Does it help the current folks who did not have successfully formed relay lists, follow lists? 

During onboarding did the changes you made prevent limbo state, or reduce chance of limbo state happening in the first place?

**Comment by danieldaquino** [comment] 2024-04-23 00:01
> Is the first aid always a manual action?

Yes, I made it a manual action for two reasons:
1. Due to the decentralized nature of Nostr, there is no good way to tell if a user really does not have any contact list, or if a contact list is just temporarily unavailable due to network issues or relay outages.
2. On top of the above, if we try to automatically perform a reset based on some rules, and we get a false negative _(i.e. the app thinks they don't have one when they actually do)_, the consequence will be a loss of all the follow list they have.

All in all, making an automated decision on this could lead to some people inadvertently losing all of their contact list, which would really really bad, so I chose to leave it a manual action to prevent this.

> Does it help the current folks who did not have successfully formed relay lists, follow lists?

Yes, this First Aid option was made specifically for those folks!

> During onboarding did the changes you made prevent limbo state, or reduce chance of limbo state happening in the first place?

Yes, I also made changes to increase robustness and prevent this issue in the first place. To summarize those changes:
1. The initial contact list is now saved locally to NostrDB during onboarding even before the app connects to any relay _(to make sure we have one even if the network connections fail to send it to the network)_
2. The latest known contact list is now also loaded directly from NostrDB during app startup, to make sure it gets loaded even if there are network or relay issues.

**Comment by alltheseas** [comment] 2024-04-23 01:56
Thanks Daniel for the comprehensive and thoughtful approach.

**Comment by jb55** [comment] 2024-04-23 15:46
On Mon, Apr 22, 2024 at 04:19:48PM GMT, Daniel D’Aquino wrote:
>Sent the patch!
>
>Details in https://groups.google.com/a/damus.io/g/patches/c/a8kI0CO2yOc
>
>@jb55, @alltheseas, if you don't get a chance to see the contact list First Aid in action, here is how the flow looks like:

looks great!

**Comment by danieldaquino** [comment] 2024-04-30 00:17
@jb55 we forgot to push this to [v1.8_relay_fix_and_video_player](https://github.com/damus-io/damus/commits/v1.8_relay_fix_and_video_player/).

Can I go ahead and cherry-pick the commits from master to that branch?

**Comment by jb55** [comment] 2024-04-30 13:58
On Mon, Apr 29, 2024 at 05:17:59PM -0700, Daniel D’Aquino wrote:
>@jb55 we forgot to push this to [v1.8_relay_fix_and_video_player](https://github.com/damus-io/damus/commits/v1.8_relay_fix_and_video_player/).
>
>Can I go ahead and cherry-pick the commits from master to that branch?

sure! I'm not sure what that branch is.

**Comment by danieldaquino** [comment] 2024-05-01 16:46
> On Mon, Apr 29, 2024 at 05:17:59PM -0700, Daniel D’Aquino wrote: @jb55 we forgot to push this to [v1.8_relay_fix_and_video_player](https://github.com/damus-io/damus/commits/v1.8_relay_fix_and_video_player/). Can I go ahead and cherry-pick the commits from master to that branch?
> sure! 

Sounds good, I will do that now and then close this ticket

> I'm not sure what that branch is.

That branch is the one for the 1.8 AppStore release

**Comment by danieldaquino** [comment] 2024-05-01 17:07
Cherry-picked the commits associated with this ticket:
- 279854a9
- 19ba020b
- 43a5bbd5

to the 1.8 release branch at https://github.com/damus-io/damus/commits/v1.8_relay_fix_and_video_player/

Closing this ticket!

**Closed by danieldaquino** 2024-05-01 17:07 UTC
Labels: bug, onboarding, technical, Needs recreation
