### ISSUE TITLE
Convert noteID in ellipsis menu to neventID

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1843] opened 2023-12-27 21:18 UTC
![image](https://github.com/damus-io/damus/assets/64376233/69b7b92c-6610-4b0e-87e7-638e9af96038)

**Comment by kernelkind** [comment] 2024-02-01 21:04
@alltheseas close this, it's a duplicate of https://github.com/damus-io/damus/issues/1844

**Closed** 2024-02-01 21:16 UTC
Labels: duplicate 📄📄, enhancement +
