### ISSUE TITLE
Bug: something wrong with the damus.io/key

### ISSUE THREAD

**Issue by Falci** [damus-io/damus#2148] opened 2024-04-16 07:31 UTC
It seems like there's a problem with the page https://damus.io/key/

![image](https://github.com/damus-io/damus/assets/1330573/e7f3ef03-c36e-409e-bae5-6875ee0e6ad3)

Sorry for skipping the issue template, but it doesn't seem relevant.

**Comment by alltheseas** [comment] 2024-04-16 14:59
What exactly is wrong? Is it the broken CSS, or is it the key conversion tool?

**Comment by alltheseas** [comment] 2024-04-16 15:00
Probably duplicate of https://github.com/damus-io/website/issues/19

**Closed by alltheseas** 2024-04-16 15:00 UTC
Labels: bug, duplicate

**Comment by Falci** [comment] 2024-04-16 15:01
Broken CSS. The tool works.

**Comment by jb55** [comment] 2024-04-17 20:16
On Tue, Apr 16, 2024 at 08:02:20AM -0700, Fernando Falci wrote:
>Broken CSS. The tool works.

people still use this??

**Comment by jb55** [comment] 2024-04-17 20:20
On Wed, Apr 17, 2024 at 01:16:04PM -0700, William Casarin wrote:
>On Tue, Apr 16, 2024 at 08:02:20AM -0700, Fernando Falci wrote:
>>Broken CSS. The tool works.
>
>people still use this??

ok I fixed the css
