### ISSUE TITLE
Damus doesn't like closing brackets in URLs

### ISSUE THREAD

**Issue by kristapsk** [damus-io/damus#1405] opened 2023-07-31 18:46 UTC
Some Wikipedia links, for example, become unclickable (goes to wrong URL) because of that.

![image](https://github.com/damus-io/damus/assets/4500994/e77e6c00-c9ea-4034-ba46-0853227c2564)

**Comment by jb55** [comment] 2023-07-31 19:24
On Mon, Jul 31, 2023 at 11:46:33AM -0700, Kristaps Kaupe wrote:
>Some Wikipedia links, for example, become unclickable (goes to wrong URL) because of that.
>
>![image](https://github.com/damus-io/damus/assets/4500994/e77e6c00-c9ea-4034-ba46-0853227c2564)

event though it's annoying when ) is interepreted when doing something like 'my site (https://jb55.com)', we should probably still do the proper thing and intrepret it as part of the url.

Our editor should preview this.

**Comment by alltheseas** [comment] 2023-07-31 20:34
Seems like duplicate of https://github.com/damus-io/damus/issues/1027

I think @joelklabo had a PR for this - did we merge it @jb55 ?

**Comment by kristapsk** [comment] 2023-07-31 20:42
> Seems like duplicate of #1027

Yes, it is. I was searching in existing issues for "link", "links", but not "URL".

**Comment by alltheseas** [comment] 2023-07-31 20:53
Thanks @kristapsk I will close this issue - let's keep conversation in original report 🙏

**Closed** 2023-07-31 20:53 UTC
Labels: bug 🐞
