### ISSUE TITLE
Scrolling past video, sound continues to play

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1244] opened 2023-06-04 14:02 UTC
What happens:
In the new video player, if the sound is on and the video scrolls out of frame in timeline view, the sound continues playing on a loop. 

What I think should happen:
Video should pause or mute if it is no longer visible on screen.

Example note:
note16dvkw4tur4t7qljvnkq4knuey74l525f70d3hmxzqnw3mqhu798q7kt6dr

**Comment by alltheseas** [comment] 2023-06-04 14:06
Duplicate of https://github.com/damus-io/damus/issues/1238 

Can you kindly close this
Issue

**Comment by dmnyc** [comment] 2023-06-04 14:48
Closed as duplicate

**Closed** 2023-06-04 14:47 UTC
