### ISSUE TITLE
DM: URL text poor contrast in dark mode [UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#572] opened 2023-02-12 07:19 UTC
Light violet URL text on light pink is poor contrast in DM view with dark system settings. Consider changing font color or background color to improve contrast.

![image](https://user-images.githubusercontent.com/64376233/218298245-8dfadf7d-dfe0-443b-8b9c-3c688d920f0c.png)

**Comment by eval** [comment] 2023-02-12 13:05
Dupe of #457 ?

**Closed as completed** 2023-02-12 14:40 UTC
