### ISSUE TITLE
Notification also appears to the user who boosted someone's post.

### ISSUE THREAD

**Issue by scoder1747** [damus-io/damus#130] opened 2022-12-24 16:13 UTC
If I boosted someone's post, I _should not_ receive notification. Attached the video below.

https://user-images.githubusercontent.com/120697811/209443759-a84b5c62-2210-4f51-ab74-ac4f08e68a0c.MP4

**Comment by bebopkid** [comment] 2022-12-26 16:18
Duplicate of #100

**Closed** 2024-05-06 21:55 UTC
Labels: duplicate
