### ISSUE TITLE
Mute Users Temporarily

### ISSUE THREAD

**Issue by crimsonleaf363** [damus-io/damus#1685] opened 2023-11-04 14:11 UTC
### **Feature Request:**

Allow users to temporarily mute another user's content and notifications for a predetermined time, like 24hrs, 48hrs, or 72hrs. This could be integrated as a quick action when muting a user.

**Comment by alltheseas** [comment] 2023-11-05 00:29
Duplicate of https://github.com/damus-io/damus/issues/1452

**Closed** 2023-11-05 00:29 UTC
