### ISSUE TITLE
Feature Request: mute Vs MUTE

### ISSUE THREAD

**Issue by realjode** [damus-io/damus#2195] opened 2024-04-29 12:14 UTC
Regarding the #nostr muting business:

It would be great if when we mute someone it would be like a Sparta kick into the blackness of space with the user never seeing the muted again.

At the moment, if I mute a user I will still their notes if a followed user ‘quotes’ one of the muted users notes.

Would it be possible to have a Sparta mute ?

I think this may help those that want to move on from someone or something they just don’t ever want too see.

💜🫂

**Comment by alltheseas** [comment] 2024-04-29 15:55
@realjode can you provide specific examples which you expect to be not shown after you "mute"?

For example, see https://github.com/damus-io/damus/issues/1934

Use the following format:

-what happens
-what you expect to happen
-steps 1, 2, 3.. to recreate
-screenshots, screen recording
-relevant noteID, npub etc
-any other context

**Comment by alltheseas** [comment] 2024-05-06 15:53
> At the moment when I mute a user I still get notes in my feed that display 'note you've muted' Like this v
> 
> ![22EC333D-8393-4C4E-BE41-A5171E22C9FA_1_105_c](https://private-user-images.githubusercontent.com/143953225/328169286-e9eb35a0-1533-4d77-9e9e-fd7835bffa74.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTAyNzEsIm5iZiI6MTcxNTAwOTk3MSwicGF0aCI6Ii8xNDM5NTMyMjUvMzI4MTY5Mjg2LWU5ZWIzNWEwLTE1MzMtNGQ3Ny05ZTllLWZkNzgzNWJmZmE3NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTUzOTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJjOWU2OTllNDNmODRiNWJjNWI4MDhlMzMyYzdiNTc5N2IzYzI0ZTIyNzE0OTBlYjA3YjkzNzQ2NzA0YTRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3E1m3pLFXDfA6_xYvVYvWn05VEcz_Ha4G8Vil-i6E9I)
> 
> I don't want to see reposted notes from users I have muted. I don't rly want to see or here from them again.
> 

This is a duplicate of https://github.com/damus-io/damus/issues/1934


> It would be nice to have a mute option that compleatly removed the users notes or comments from my feed. Like a super mute or a spartan kick into the blackness of space coukd this be added to the Mute menu maybe? 1-Mute user 2-Remove from all
> 
> I am not having issues with muting and I havent suffered any distress, The super MUTE may be helpful to those that do want to remove someone from their experience compleatly though.
> 
> rj

Got you. Let me know if you come up with more specific examples of where you've muted someone, and you continue seeing their notes. 

Closing as duplicate.

**Closed by alltheseas** 2024-05-06 15:53 UTC
Labels: feature

**Comment by jb55** [comment] 2024-05-06 20:21
what about replies to muted posts? should we sparta mute those too ?

**Comment by realjode** [comment] 2024-05-07 11:30
That’s a good point. 
I don’t think so no. 
Just give the option to Sparta Mute the user. 
This is far more complex than I’d first thought though.. 🤔
