### ISSUE TITLE
Timed mute isn’t working

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2232] opened 2024-05-09 14:30 UTC
Reported by boston wine:

https://damus.io/nevent1qqsgx9u5fv839gqxucvv8va7wdssj5wuulfwc3vfrd9qyqj7k3p9t2qprfmhxue69uhhyetvv9ujumn0wd68yurvv438xtnrdakszxnhwden5te0wfjkccte9ehhyctwvajhq6tvdshxgetkqyg8wumn8ghj7vf5xqhxvdm69e5k7qgewaehxw309ar5znzptpvnzvewdehhxarjxyhxxmmd53z7nl

> Hey @damus team, are we sure the “mute for X time” function is working?
> I’ve tried it on a user and a thread today, muting for 24 hours and for 1 month, restarted the client, and the notes still appear. When I instead chose “mute indefinitely” it worked fine, but I was just looking for a break from these notes, not a block of the account.
> Would examples help or is this enough info?
> Cc @elsat @jb55 (not sure who on the team owns the mute feature these days)

**Comment by alltheseas** [comment] 2024-05-09 14:33
Duplicate of https://github.com/damus-io/damus/issues/2139

**Closed** 2024-05-09 14:34 UTC
Labels: duplicate
