### ISSUE TITLE
Relays intermittently not connecting

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1589] opened 2023-10-08 17:59 UTC
After keeping Damus open for a few minutes I usually run into a problem where around half of my relays stop connecting. 

In the timeline view the counter rapidly changes and in the Relay screen it shows many of them failing to connect. 

Restarting the app fixes this temporarily, but the problem soon returns. 

Additionally I think this may be what's causing the timeline scroll to stutter. 

Screen capture:
https://github.com/damus-io/damus/assets/3638467/b87d64cd-1796-4a11-b714-79f7eb225faf

**Comment by alltheseas** [comment] 2023-10-08 21:53
Which iOS and Damus version?

**Comment by dmnyc** [comment] 2023-10-08 21:57
1.6 (23) 1fabd4c0fe98

iPhone 13 Pro Max

17.0.3

**Comment by alltheseas** [comment] 2023-10-09 00:32
@danieldaquino is this related to

https://github.com/damus-io/damus/issues/1531

@jb55 if I remember correctly we previously had this issue, and it was fixed

**Comment by danieldaquino** [comment] 2023-10-09 18:29
@alltheseas, I think it is unlikely to be related to #1531, but I will keep that ticket in mind when investigating this as a possible factor.

**Comment by alltheseas** [comment] 2023-10-09 18:40
Here is a similar prior instance 

https://github.com/damus-io/damus/issues/1132

**Comment by jb55** [comment] 2023-10-11 05:03
On Sun, Oct 08, 2023 at 10:59:40AM -0700, Maybe: Daniel ?️ wrote:
>After keeping Damus open for a few minutes I usually run into a problem where around half of my relays stop connecting.
>
>In the timeline view the counter rapidly changes and in the Relay screen it shows many of them failing to connect.
>
>Restarting the app fixes this temporarily, but the problem soon returns.

I rarely hit this, but I have seen it>

>Additionally I think this may be what's causing the timeline scroll to stutter.

likely, since it resends filters on reconnect. we should figure out why
exponential fallback is not working as well. it should not be
reconnecting this rapidly.

**Comment by alltheseas** [comment] 2023-10-11 15:57
I'll suggest this for next sprint as a high priority item @danieldaquino

**Comment by jb55** [comment] 2023-10-14 09:19
On Wed, Oct 11, 2023 at 08:57:38AM -0700, alltheseas wrote:
>I'll suggest this for next sprint as a high priority item @danieldaquino

reproducing random connectivity issues might be difficult.

**Comment by alltheseas** [comment] 2024-08-19 19:05
Adding reference to relay performance / connectivity issue https://github.com/damus-io/damus/issues/2343 and closing

**Closed by alltheseas** 2024-08-19 19:05 UTC
Labels: Needs recreation, regression, rabbit-hole, relay
