### ISSUE TITLE
Notification on DM Icon appears at Sender side after DM is sent.

### ISSUE THREAD

**Issue by scoder1747** [damus-io/damus#129] opened 2022-12-23 21:39 UTC
There is no need of the blue dot notification appearing on DM Icon on sender side after a message is sent. Only Receiver should be notified about receiving of the message.

https://user-images.githubusercontent.com/120697811/209407666-4a50b16f-6d57-4d67-923d-005d3540c938.mov

**Comment by bebopkid** [comment] 2022-12-23 23:11
Duplicate of #100

**Closed** 2024-05-06 21:55 UTC
Labels: bug, duplicate
