### ISSUE TITLE
Bug: Erroneous zap notifications received when zapping replies to my own notes

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#2477] opened 2024-09-14 14:45 UTC
What happens: When zapping replies to my notes I am receiving notifications that I zapped myself. 

This is an example zap event where this occurs:
note1cjhlna39502jw68ppxyf9ls0yzed5w4eksfug5are0pj7055gugscu9y22

Screenshots:
![image](https://github.com/user-attachments/assets/161f4b85-2de7-4197-a3db-a8ea17fedd53)
![image](https://github.com/user-attachments/assets/ea44bea1-a7d0-4ac1-ba95-c7ccb8ed02c9)

**Comment by jb55** [comment] 2024-09-14 14:51
Duplicate of https://github.com/damus-io/damus/issues/2462 we know the root cause, we are in the process of fixing it

**Closed by jb55** 2024-09-14 14:51 UTC
Labels: bug, Needs recreation
