### ISSUE TITLE
Negentropy syncing

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1407] opened 2023-07-31 21:47 UTC
# Technical 

// I have no idea what this is, but nostrdb (https://github.com/damus-io/damus/issues/1406) enables this, and Will is planning work on this

**Comment by alltheseas** [comment] 2023-07-31 22:06
@jb55 what is negentropy sync, and what are the benefits & unlocks of this?

**Comment by alltheseas** [comment] 2023-08-02 17:28
negentropy sync - documentation set reconciliation - supported by damus relay (P Wuille does this)
give all contacts list that I dont have (for this query)
does magical reconciliation
efficient way
it follows that
with nostrdatabase - consistent follow counts will be possible

**Comment by jb55** [comment] 2023-08-04 16:25
Training session with GPT4

https://chat.openai.com/share/00078bea-9349-477b-ba5d-e3c29a345449

**Comment by jb55** [comment] 2023-08-04 19:11
duplicate of https://github.com/damus-io/nostrdb/issues/3

keeping issues in their respective repos for now

**Closed by jb55** 2023-08-04 19:11 UTC
Labels: technical 🧙‍♂️, Performance 🐢🐇

**Comment by alltheseas** [comment] 2023-08-04 19:26
Didn't know there was a nostrdb repo - got it.
