### ISSUE TITLE
Mentions in translated notes appear as plain text

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2011] opened 2024-02-15 17:16 UTC
_what happens_

Translated note using purple deepL service that includes a mention translates the mention to plain text

_question / suggestion_

> When a note that contains a mention is translated, the mention is rendered as plain text instead of as a mention. I think it would look cleaner if the translated text contained mentions. This can be done by converting the translated string to Blocks and then rendering the blocks like a normal note

@kernelkind

**Comment by alltheseas** [comment] 2024-02-15 18:44
Similar problem to longform notes mention not rendering https://github.com/damus-io/damus/issues/1743

**Comment by kernelkind** [comment] 2024-02-15 21:00
I looked through the code and I'm realizing that translated notes are already converted to blocks & render mentions properly. The problem is that the translation service thinks nostr addresses are a foreign language and are attempting to translate them. 

<img width="405" alt="image" src="https://github.com/damus-io/damus/assets/8139906/c0bd6260-7c90-484d-9cad-7b99e37fe606">

https://damus.io/nevent1qqs0355wrutwgz33znldza94cqwc7tgllcxs7hl0d9l4ac6uy0yrk8qpz9mhxue69uhkummnw3eryvfwvdhk6qghwaehxw309a3hyetpw3ezumn0wd68ytnhd9hx2qgdwaehxw309ahx7uewd3hkcqg5waehxw309aex2mrp0yhxummnw3ezucn8gkdz2v

This note has the mention:
`nevent1qqsxtzmk6d05r3s3xxcwma26txmjekvt45c82mrshzuqew96dpnckvqpp4mhxue69uhkummn9ekx7mqzyr6dk5nshkv3k9a758ndqd05thhrj2gec228fwavzq6z6g3uwnsdqqcyqqqqqqg0yfkk8`

But the translated version has the mention:
`nevent1qqsxtzmk6d05r3s3xxcwma26txmjekvt45c82mrshzuqew96dpnckvqpp4mhxue69uhkummn9ekx7mqzyr6dk5nshkv3k9a758ndqd05thhrj2gec228fwavzq6z6g3uwnsdqqcyqqqqg0yfkk8`

**Comment by kernelkind** [comment] 2024-02-16 19:42
I don't really see a way around this. One way that would technically work is packaging 'non-mentions' into 'blocks' and sending them to the translation service separately. Then stitching the translated text with the mentions. So this would require sending ~N translation requests per note (where N is number of mentions), and I imagine that would be too costly of a solution

**Comment by jb55** [comment] 2024-02-22 18:03
On Fri, Feb 16, 2024 at 11:42:23AM -0800, kernelkind wrote:
>I don't really see a way around this. One way that would technically
>work is packaging 'non-mentions' into 'blocks' and sending them to the
>translation service separately. Then stitching the translated text with
>the mentions. So this would require sending ~N translation requests per
>note (where N is number of mentions), and I imagine that would be too
>costly of a solution

we should look at deepl docs and see if we can make placeholders of some
kind that are not translated

**Comment by kernelkind** [comment] 2024-02-23 23:00
The API accepts the text as an array, with up to [50 entries](https://www.deepl.com/docs-api/translate-text) per translation request.

```
curl -X POST 'https://api.deepl.com/v2/translate' \
--header 'Authorization: DeepL-Auth-Key [yourAuthKey]' \
--header 'Content-Type: application/json' \
--data '{
  "text": [
    "Hello, world!"
  ],
  "target_lang": "DE"
}'
```

The API also allows for [XML tag handling](https://www.deepl.com/docs-api/xml).
<img width="882" alt="image" src="https://github.com/damus-io/damus/assets/8139906/afdd4d88-a2c2-461e-b4bb-3d34719ac999">

So I see two options for fixing this issue:
1. We split the note up into chunks which don't contain mentions and populate them into the array for translation. Then after receiving the translation we can bring the mentions back in to the text.
2. We add XML tags around each mention and tell the API which tags to ignore.

I think the second option sounds like the better solution

**Comment by kernelkind** [comment] 2024-02-24 17:35
This would probably involve adding a new method to the api. 

Here's the current deepl api caller:
https://github.com/damus-io/api/blob/47475fca2c27d45ec2bbd74a73905a3d8565f9ee/src/translate.js#L38-L60

We can add a new method similar to this one, say `deepl_translate_xml_text` which would add the needed parameters for xml:
```
    body: JSON.stringify({
      text: payload.xml,
      source_lang: payload.source,
      target_lang: payload.target,
      tag_handling: "xml",
      ignore_tags: ["x"],
    })
```

We would add the `xml` query parameter to the api request. Then a similar method can be created in `damus` for sending the request, which sends the text string with xml tags around each mention:
https://github.com/damus-io/damus/blob/1214f1839d78d2d96e7be32532e294570f9682d9/damus/Models/Purple/DamusPurple.swift#L192-L207

**Comment by alltheseas** [comment] 2024-04-26 16:17
@jb55  does @semisol upgrade fix this?

**Comment by jb55** [comment] 2024-04-28 02:57
should be fixed now on noswhere backend

**Closed by jb55** 2024-04-28 02:57 UTC
Labels: localization, purple, unexpected
