### ISSUE TITLE
iOS 18; opening image turns app to dark mode

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2460] opened 2024-09-10 20:07 UTC
**What happens**
When I open an image app switches to dark mode. iOS 18 beta

https://damus.io/note1su5p3qa8xc257zgqjp89j0pw3ntnhlgcjw3vk4330ty7llltk0lqkx6852

**Comment by jb55** [comment] 2024-09-10 20:21
duplicate of 

- https://github.com/damus-io/damus/issues/2373

**Closed by jb55** 2024-09-10 20:21 UTC
Labels: bug, Needs recreation, ios 18
