### ISSUE TITLE
Make DMs respect mute list

### ISSUE THREAD

**Issue by onedrop** [damus-io/damus#1350] opened 2023-07-06 16:20 UTC
two issues i've observed when using the mute feature...

- DMs from muted accounts still appear and are unobfuscated
- if someone reposts a note from a user you have muted, it still appears in the timeline unobfuscated

**Comment by alltheseas** [comment] 2023-07-07 03:15
Latter is duplicate of https://github.com/damus-io/damus/issues/1216. Thanks for reporting DMs mute issue.

**Comment by alltheseas** [comment] 2023-07-20 14:04
Mute likes of reply of someone you've muted

https://damus.io/note1pf5hs3x825rykecxtddyh0xynk8t4kfm25cv94cqsf6p2vuc65wsfwxfhg

**Comment by bryanmontz** [comment] 2023-07-25 11:53
@alltheseas I just tested this using two accounts, and I couldn't reproduce it for DMs. It seemed to work as I expected, showing messages and notifications while the other user was not muted and hiding the conversation altogether while the other user was muted. Are there steps to reproduce?

**Comment by alltheseas** [comment] 2023-07-25 15:21
> I dont have exact steps but i have users in my mute list and their conversations with me still appear in the DM list view (on the ‘DMs’ tab)

Did the conversation start before you muted them?

**Comment by onedrop** [comment] 2023-07-25 15:33
> > I dont have exact steps but i have users in my mute list and their conversations with me still appear in the DM list view (on the ‘DMs’ tab)
> 
> Did the conversation start before you muted them?

yes, it did start before muting them. maybe that's the reason you aren't able to reproduce it.

**Comment by jb55** [comment] 2023-07-25 15:38
On Tue, Jul 25, 2023 at 08:34:02AM -0700, onedrop wrote:
>> > I dont have exact steps but i have users in my mute list and their conversations with me still appear in the DM list view (on the ‘DMs’ tab)
>>
>> Did the conversation start before you muted them?
>
>yes, it did start before muting them. maybe that's the reason you aren't able to reproduce it.

looks like we just need to apply a filter to the DMs after muting

**Comment by alltheseas** [comment] 2023-10-02 15:51
> On Tue, Jul 25, 2023 at 08:34:02AM -0700, onedrop wrote: > > I dont have exact steps but i have users in my mute list and their conversations with me still appear in the DM list view (on the ‘DMs’ tab) > > Did the conversation start before you muted them? yes, it did start before muting them. maybe that's the reason you aren't able to reproduce it.
> looks like we just need to apply a filter to the DMs after muting

Did you apply this filter already Will?

I just DM's self from a test profile, muted said profile, and the DM disappeared.

**Comment by alltheseas** [comment] 2023-10-02 15:54
![image](https://github.com/damus-io/damus/assets/64376233/20075353-46c5-4054-917b-a4402198d0f5)

**Comment by onedrop** [comment] 2023-10-02 18:22
convos with muted users still appear in the DM list view for me as of testflight 1.6 (19)

**Comment by alltheseas** [comment] 2023-10-02 18:29
> convos with muted users still appear in the DM list view for me as of testflight 1.6 (19)

@onedrop can you provide the steps to recreate this issue 🙏

**Comment by jb55** [comment] 2023-10-02 18:39
On Mon, Oct 02, 2023 at 08:52:05AM -0700, alltheseas wrote:
>> On Tue, Jul 25, 2023 at 08:34:02AM -0700, onedrop wrote: > > I dont have exact steps but i have users in my mute list and their conversations with me still appear in the DM list view (on the ‘DMs’ tab) > > Did the conversation start before you muted them? yes, it did start before muting them. maybe that's the reason you aren't able to reproduce it.
>> looks like we just need to apply a filter to the DMs after muting
>
>Did you apply this filter already Will?
>
>I just DM's self from a test profile, muted said profile, and the DM disappeared.

yes I thought I fixed this a long time ago

**Comment by jb55** [comment] 2023-10-02 18:45
>>Did you apply this filter already Will?
>>
>>I just DM's self from a test profile, muted said profile, and the DM disappeared.
>
>yes I thought I fixed this a long time ago

maybe there's an issue with requests specifically? or it could be a new
account that looks like the muted one?

**Comment by alltheseas** [comment] 2023-10-02 19:11
> could be a new account that looks like the muted one?

@onedrop can you confirm if this is the case? You can do this by confirming the npub

**Comment by onedrop** [comment] 2023-10-02 20:05
ok hard to tell whats going on. seems like it does indeed filter it but it doesn't last. upon killing the app and relaunching, the filter is no longer applied. maybe its cached somehow and not getting cache busted. 

- go to dm list view and scroll to any user you have started a DM convo with
- click on their profile pic to nav to their profile page
- click the `...` next to one of their posts and select `Mute user`
- go back to the DM list view... observe muted users no longer appears in the list of DMs
- now, kill the app via ios app switcher
- go back to DM list view... observe muted list is no longer being applied

**Comment by alltheseas** [comment] 2023-10-03 14:21
@onedrop can you replicate using mute from profile view?

![image](https://github.com/damus-io/damus/assets/64376233/1e36b8ff-c6a5-40d7-894c-64a68f736342)

**Comment by onedrop** [comment] 2023-10-03 15:22
> @onedrop can you replicate using mute from profile view?

same issue for me when muted that way.

**Comment by alltheseas** [comment] 2023-10-03 16:31
Replicated, albeit with a lengthy delay. 

Applies for both muting a profile prior to receiving a DM from the muted profile, and after. 

![image](https://github.com/damus-io/damus/assets/64376233/2af354fa-92d6-44a9-894d-fa10433064e8)

**Comment by alltheseas** [comment] 2023-10-03 16:33
@danieldaquino if you are done early with the current sprint commitment, and you don't have anything you'd like to tinker with I suggest this issue. 

If we don't get to it this sprint, I'll propose for the following sprint.

**Comment by danieldaquino** [comment] 2023-10-16 23:58
> * if someone reposts a note from a user you have muted, it still appears in the timeline unobfuscated

**Note:** This one has been fixed in https://github.com/damus-io/damus/issues/1216

> * DMs from muted accounts still appear and are unobfuscated

Reproduced this one using steps provided here: https://github.com/damus-io/damus/issues/1350#issuecomment-1743679175. 

I am currently investigating the root cause for this one.

**Comment by danieldaquino** [comment] 2023-10-17 01:38
Created a fix for this! All code, discussion, and testing was sent via email and can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/bSm7xo1mHfc

**Closed** 2023-10-17 23:04 UTC
Labels: bug 🐞, good first issue 😌, DM ✉️
