### ISSUE TITLE
Deleting strange character ꙰ crash

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1631] opened 2023-10-21 02:19 UTC
> Damus 1.6 (23) has an issue with Cryllic-B characters. I can copy and paste from another app just fine, however, if I try to delete said characters, Damus crashes to the home screen. 🤙🏻

> Use  ꙰ in between the “input validation” lines and then try to backspace over the  ꙰ to remove it and poof. 🤙🏻

![image](https://github.com/damus-io/damus/assets/64376233/f82eeac7-aebe-42fa-b6ad-abfbb04732e6)![image](https://github.com/damus-io/damus/assets/64376233/0e55395a-7e00-4f44-891b-3bc7e37f416e)

https://damus.io/note1phvncnwyfvj4hvlcccguu6gwngtmk634tqpq0as3rmqrqar3w47q0pq59w

**Comment by kernelkind** [comment] 2023-12-18 14:58
Cannot reproduce crash on iphone 15 pro simulator on ios 17.2 or iphone 13 on ios 17.1.2 latest damus version

**Comment by jb55** [comment] 2023-12-18 16:19
This was probably fixed by https://github.com/damus-io/nostrdb/commit/fefb9df7cd51e3233401aad9c9508f302e903297

**Closed by jb55** 2023-12-18 16:19 UTC
Labels: bug 🐞, good first issue 😌

**Comment by alltheseas** [comment] 2023-12-18 18:54
@geeknik fyi
