### ISSUE TITLE
Intro note submit button doesn't leave screen but posts multiple of the same note

### ISSUE THREAD

**Issue by johnshenio** [damus-io/damus#1726] opened 2023-11-17 01:17 UTC
The new update on my iPhone 12 pro, iOS 17 with the introduction notes posts multiple of the same button after clicking the submit button. The submit button doesn't leave the post creation screen

I created a new npub but I couldn't get back to the intro note screen

**Comment by alltheseas** [comment] 2023-11-17 01:51
Thanks for reporting. I believe this is a duplicate of https://github.com/damus-io/damus/issues/1502

**Comment by jb55** [comment] 2023-11-17 01:54
I believe this is different

**Comment by alltheseas** [comment] 2023-11-17 02:25
Another instance. https://damus.io/note1ur90wv38g06hkqe0kc6wyt6tfnke629u0arxtcsa2fezjswq5yfstn0t9g

https://damus.io/note1grfy7f0g8qgzfym7esg9k92yjqx8rcrqnvgy4c6tga9pzzcq886se5sqqg

**Comment by alltheseas** [comment] 2023-11-17 02:34
One more

https://damus.io/note1jnm8m0e39ne78mfgvt4gnhuh54jh3gv7uyqg8pkzf3q0p448r96squlg78

![image](https://github.com/damus-io/damus/assets/64376233/bef38333-0481-4ef6-9900-f9a26f591475)

**Comment by jb55** [comment] 2023-11-17 02:43
this is really bad

**Comment by alltheseas** [comment] 2023-11-17 02:46
https://damus.io/note1v0qrywwy8zul5zmlrvn9z3gy8p8qw8j2tucwksxz26k85nt8wnqsv5uzdk

**Comment by alltheseas** [comment] 2023-11-17 02:51
Is it possible to get a quick fix in, or remove this code for now?

cc @danieldaquino

**Comment by danieldaquino** [comment] 2023-11-17 03:29
@alltheseas, @jb55, I believe this is precondition dependent.

Two examples:

**Device:** iPhone 15 Pro simulator
**iOS:** 17.0
**Damus:** v1.6 (29) (`f976f23854dfddc390bf00095c69d27460c6776d`) (Local build)
**Behavior:** Post view dismissed after posting (works)

**Device:** iPhone 13 Mini
**iOS:** 17.1
**Damus:** v1.6 (29) (`f976f23854dfddc390bf00095c69d27460c6776d`) (Official build)
**Behavior:** Post view NOT dismissed after posting

**Comment by danieldaquino** [comment] 2023-11-17 03:30
I suspect this might be due to our use of `.presentationMode`, which upon checking, seems to be deprecated.

https://developer.apple.com/documentation/swiftui/environmentvalues/presentationmode?changes=latest_major

I will check if that's indeed the root cause

**Comment by danieldaquino** [comment] 2023-11-17 03:37
Device: iPhone 13 Mini
iOS: 17.1
Damus: v1.6 (29) (f976f23854dfddc390bf00095c69d27460c6776d) (Local build)
Behavior: Post view NOT dismissed after posting

**Comment by danieldaquino** [comment] 2023-11-17 03:44
Original passing test preconditions (from bf43842590a0f62aafcd0f811d0634b396ab7f6e)

Device: iPhone 14 Pro simulator
iOS: 17.0
Damus: bf43842590a0f62aafcd0f811d0634b396ab7f6e

**Comment by danieldaquino** [comment] 2023-11-17 03:46
> I suspect this might be due to our use of `.presentationMode`, which upon checking, seems to be deprecated.
> 
> https://developer.apple.com/documentation/swiftui/environmentvalues/presentationmode?changes=latest_major
> 
> I will check if that's indeed the root cause

It does not seem to be the only cause. Changing it to the new `dismiss()` also did not work

**Comment by danieldaquino** [comment] 2023-11-17 04:02
@jb55, this is starting to look like one of those obscure SwiftUI bugs.

**The relevant factors that determine whether or not the bug occurs seem to be one or many of these:**
- iOS version: Tests on 17.0 work as far as I have tested, Tests on 17.1 fail as far as I have tested
- Real device vs. simulator: Simulator works as far as I have tested, real devices do not seem to work as far as I have tested
- View hierarchy: Normal posts seem to be unaffected. However, the _exact same post view_ under the onboarding seems to fail.

In the interest of time, I will send a patch to temporarily disable this onboarding feature

**Comment by alltheseas** [comment] 2023-11-17 04:14
> this is starting to look like one of those obscure SwiftUI bugs.

Does this experience make the case for UIkit?

**Comment by danieldaquino** [comment] 2023-11-17 04:32
> > this is starting to look like one of those obscure SwiftUI bugs.
> 
> Does this experience make the case for UIkit?

Maaaybe, UIKit also has some weird quirks (e.g. the text editor wrapping bugs) LOL

**Comment by danieldaquino** [comment] 2023-11-17 04:39
@jb55, I sent an emergency patch for temporarily disabling the feature: https://groups.google.com/a/damus.io/g/patches/c/T6pqnIhJzHc

I will work on a full clean fix tomorrow. I believe the root cause is a combination of:
- Inconsistent behavior of the environment variable `.presentationMode` between iOS versions or whether the device is real or a simulator (The deprecation might explain the inconsistency)
- The new environment variable `.dismiss` seems to have limited propagation. It works on `OnboardingSuggestionsView`, but not on any of its subviews (At least on iOS 17.1 + iPhone 13)

If you could double-check my testing under a different precondition I would appreciate 🙏 (we don't know yet the extent of the inconsistencies around this).

**Comment by jb55** [comment] 2023-11-17 14:37
On Thu, Nov 16, 2023 at 08:14:16PM -0800, alltheseas wrote:
>> this is starting to look like one of those obscure SwiftUI bugs.
>
>Does this experience make the case for UIkit?

that would be a huge change, it would take months

**Comment by danieldaquino** [comment] 2023-11-17 20:11
@jb55, @alltheseas, sent a patch with the fix!

Root causing, code, fix explanation, and testing report are all in the patch email (Can be viewed here: https://groups.google.com/a/damus.io/g/patches/c/DJ8XymT9mHA)

**Important notes:**
- I observed another issue _(not as bad as this one)_ on iOS 16. I reported it under a separate ticket: https://github.com/damus-io/damus/issues/1739
- I made this patch directly on top of the current release. We probably want to create a hotfix branch where we merge in only essential fixes, to avoid regression risk from other recent changes in `master`
- I tried to test as much and as carefully as possible, but I appreciate any extra independent testing to make sure I did not miss anything 🙏

**Comment by jb55** [comment] 2023-11-20 16:31
On Fri, Nov 17, 2023 at 12:11:54PM -0800, Daniel D’Aquino wrote:
>@jb55, @alltheseas, sent a patch with the fix!
>
>Root causing, code, fix explanation, and testing report are all in the patch email (Can be viewed here: https://groups.google.com/a/damus.io/g/patches/c/DJ8XymT9mHA)

awesome, will see if I can get a hotfix out

**Closed** 2023-11-20 16:36 UTC
Labels: bug 🐞
